<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-07 at 05:34:46.
 */
class CreateUsersTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CreateUsers
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CreateUsers;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers CreateUsers::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->object->__destruct();
        if (isset($this->object))
            throw new Exception("Nie dziala destruktor. ");
    }

    /**
     * @covers CreateUsers::getNr_SIP_klienta
     * @todo   Implement testGetNr_SIP_klienta().
     */
    public function testGetNr_SIP_klienta() {
        $this->object->setNr_klienta('10000');
        $this->object->getNazwa_klienta();        
    }

    /**
     * @covers CreateUsers::setNr_SIP_klienta
     * @todo   Implement testSetNr_SIP_klienta().
     */
    public function testSetNr_SIP_klienta() {
        $this->object->setNr_klienta('10000');
    }

    /**
     * @covers CreateUsers::getNr_SIP_c2c
     * @todo   Implement testGetNr_SIP_c2c().
     */
    public function testGetNr_SIP_c2c() {
        $this->object->setNr_SIP_c2c('90000');
        $this->object->getNr_SIP_c2c();
    }

    /**
     * @covers CreateUsers::setNr_SIP_c2c
     * @todo   Implement testSetNr_SIP_c2c().
     */
    public function testSetNr_SIP_c2c() {
        $this->object->setNr_SIP_c2c('90000');
    }

    /**
     * @covers CreateUsers::getNr_klienta
     * @todo   Implement testGetNr_klienta().
     */
    public function testGetNr_klienta() {
        $this->object->setNr_SIP_c2c('10000');
    }

    /**
     * @covers CreateUsers::setNr_klienta
     * @todo   Implement testSetNr_klienta().
     */
    public function testSetNr_klienta() {
        $this->object-
    }

    /**
     * @covers CreateUsers::getNazwa_klienta
     * @todo   Implement testGetNazwa_klienta().
     */
    public function testGetNazwa_klienta() {
        $this->object-
    }

    /**
     * @covers CreateUsers::setNazwa_klienta
     * @todo   Implement testSetNazwa_klienta().
     */
    public function testSetNazwa_klienta() {
        $this->object-
    }

    /**
     * @covers CreateUsers::getHas_external_dial
     * @todo   Implement testGetHas_external_dial().
     */
    public function testGetHas_external_dial() {
        $this->object-
    }

    /**
     * @covers CreateUsers::setHas_external_dial
     * @todo   Implement testSetHas_external_dial().
     */
    public function testSetHas_external_dial() {
        $this->object-
    }

    /**
     * @covers CreateUsers::getVM_password
     * @todo   Implement testGetVM_password().
     */
    public function testGetVM_password() {
        $this->object-
    }

    /**
     * @covers CreateUsers::setVM_password
     * @todo   Implement testSetVM_password().
     */
    public function testSetVM_password() {
        $this->object-
    }

    /**
     * @covers CreateUsers::getNumer_prezentowany
     * @todo   Implement testGetNumer_prezentowany().
     */
    public function testGetNumer_prezentowany() {
        $this->object-
    }

    /**
     * @covers CreateUsers::setNumer_prezentowany
     * @todo   Implement testSetNumer_prezentowany().
     */
    public function testSetNumer_prezentowany() {
        $this->object-
    }

    /**
     * @covers CreateUsers::getUser_email
     * @todo   Implement testGetUser_email().
     */
    public function testGetUser_email() {
        $this->object-
    }

    /**
     * @covers CreateUsers::setUser_email
     * @todo   Implement testSetUser_email().
     */
    public function testSetUser_email() {
        $this->object-
    }

    /**
     * @covers CreateUsers::getUser_password
     * @todo   Implement testGetUser_password().
     */
    public function testGetUser_password() {
        $this->object-
    }

    /**
     * @covers CreateUsers::setUser_password
     * @todo   Implement testSetUser_password().
     */
    public function testSetUser_password() {
        $this->object-
    }

    /**
     * @covers CreateUsers::GenerateNewIVR
     * @todo   Implement testGenerateNewIVR().
     */
    public function testGenerateNewIVR() {
        $this->object-
    }

}
