<?php
require_once dirname(__FILE__) . '\..\..\..\create_service\system\CreateIVR.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-06 at 06:24:02.
 */
class CreateIVRTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CreateIVR
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CreateIVR;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
       // $filename = $this->object->DIRECTORY. $this->object->Nr_klienta.'-'.$this->object->Nazwa_klienta;
       // unlink($filename);
    }

    /**
     * @covers CreateIVR::SetNazwa_Klienta
     * @todo   Implement testSetNazwa_Klienta().
     */
    public function testSetNazwa_Klienta() {
        $this->object->SetNazwa_Klienta('proxyAd');
    }

    /**
     * @covers CreateIVR::GetNazwa_Klienta
     * @todo   Implement testGetNazwa_Klienta().
     */
    public function testGetNazwa_Klienta() {
        $this->object->SetNazwa_Klienta('proxyAd');
        $this->object->GetNazwa_Klienta();
    }

    /**
     * @covers CreateIVR::SetNr_klienta
     * @todo   Implement testSetNr_klienta().
     */
    public function testSetNr_klienta() {
        $this->object->SetNr_klienta('10000');
    }

    /**
     * @covers CreateIVR::GetNr_Klienta
     * @todo   Implement testGetNr_Klienta().
     */
    public function testGetNr_Klienta() {
        $this->object->SetNr_klienta('10000');
        $this->object->GetNr_klienta();
    }

    /**
     * @covers CreateIVR::GenerateNewIVR
     * @todo   Implement testGenerateNewIVR().
     */
    public function testGenerateNewIVR() {
        //Tworzenie nowego IVR'a
        $this->object->SetNazwa_Klienta('proxyAd');
        $this->object->SetNr_klienta('10000');
        $this->object->GenerateNewIVR();
    }

}
