<?php
require_once dirname(__FILE__) . '\..\..\..\create_service\system\CreateUsers.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-08 at 08:04:06.
 */
class CreateUsersTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CreateUsers
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CreateUsers;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        /**
         * @todo remove generated file here
         */
    }

    /**
     * @covers CreateUsers::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // $this->object->__destruct(); works :)
    }

    /**
     * @covers CreateUsers::getNr_SIP_klienta
     * @todo   Implement testGetNr_SIP_klienta().
     */
    public function testGetNr_SIP_klienta() {
        $this->object->setNr_SIP_klienta('10000');
        $this->object->getNr_SIP_klienta();
    }

    public function TestGet_CreateC2cUser() {
        $this->object->set_CreateC2cUser(true);

        $this->object->get_CreateC2cUser();
    }

    public function TestSet_CreateC2cUser() {
        $this->object->set_CreateC2cUser(true);
    }

    /**
     * @covers CreateUsers::setNr_SIP_klienta
     * @todo   Implement testSetNr_SIP_klienta().
     */
    public function testSetNr_SIP_klienta() {
        $this->object->setNr_klienta('10000');
    }

    /**
     * @covers CreateUsers::getNr_SIP_c2c
     * @todo   Implement testGetNr_SIP_c2c().
     */
    public function testGetNr_SIP_c2c() {
        $this->object->setNr_SIP_c2c('90000');
        $this->object->getNr_SIP_c2c();
    }

    /**
     * @covers CreateUsers::setNr_SIP_c2c
     * @todo   Implement testSetNr_SIP_c2c().
     */
    public function testSetNr_SIP_c2c() {
        $this->object->setNr_SIP_c2c('90000');
    }

    /**
     * @covers CreateUsers::getNr_klienta
     * @todo   Implement testGetNr_klienta().
     */
    public function testGetNr_klienta() {
        $this->object->setNr_klienta('10000');
        $this->object->getNr_klienta();
    }

    /**
     * @covers CreateUsers::setNr_klienta
     * @todo   Implement testSetNr_klienta().
     */
    public function testSetNr_klienta() {
        $this->object->setNr_SIP_klienta('10000');
    }

    /**
     * @covers CreateUsers::getNazwa_klienta
     * @todo   Implement testGetNazwa_klienta().
     */
    public function testGetNazwa_klienta() {
        $this->object->setNr_SIP_klienta('ProxyAd');
        $this->object->getNr_SIP_klienta();
    }

    /**
     * @covers CreateUsers::setNazwa_klienta
     * @todo   Implement testSetNazwa_klienta().
     */
    public function testSetNazwa_klienta() {
        $this->object->setNazwa_klienta('ProxyAd');
    }

    /**
     * @covers CreateUsers::getHas_external_dial
     * @todo   Implement testGetHas_external_dial().
     */
    public function testGetHas_external_dial() {
        $this->object->setHas_external_dial('false');
        $this->object->getHas_external_dial();
    }

    /**
     * @covers CreateUsers::setHas_external_dial
     * @todo   Implement testSetHas_external_dial().
     */
    public function testSetHas_external_dial() {
        //Nothing yet
    }

    /**
     * @covers CreateUsers::getVM_password
     * @todo   Implement testGetVM_password().
     */
    public function testGetVM_password() {
        $this->object->setVM_password('voicemail_pass');
        $this->object->getVM_password();
    }

    /**
     * @covers CreateUsers::setVM_password
     * @todo   Implement testSetVM_password().
     */
    public function testSetVM_password() {
        $this->object->SetVM_password('*#@$(!@(U@(*!gkwsjg');
    }

    /**
     * @covers CreateUsers::getNumer_prezentowany
     * @todo   Implement testGetNumer_prezentowany().
     */
    public function testGetNumer_prezentowany() {
        $this->object->setNumer_prezentowany("222486001");
        $this->object->getNumer_prezentowany();
    }

    /**
     * @covers CreateUsers::setNumer_prezentowany
     * @todo   Implement testSetNumer_prezentowany().
     */
    public function testSetNumer_prezentowany() {
        $this->object->setNumer_prezentowany("222486001");
    }

    /**
     * @covers CreateUsers::getUser_email
     * @todo   Implement testGetUser_email().
     */
    public function testGetUser_email() {
        $this->object->setUser_email('user@mail.com');
        $this->object->getUser_email();
    }

    /**
     * @covers CreateUsers::setUser_email
     * @todo   Implement testSetUser_email().
     */
    public function testSetUser_email() {
        $this->object->setUser_email('user@mail.com');
    }

    /**
     * @covers CreateUsers::getUser_password
     * @todo   Implement testGetUser_password().
     */
    public function testGetUser_password() {
        $this->object->setUser_password('user_password');
        $this->object->getUser_password();
    }

    /**
     * @covers CreateUsers::setUser_password
     * @todo   Implement testSetUser_password().
     */
    public function testSetUser_password() {
        $this->object->setUser_password('rtyunhyg8*&&UJKAin');
    }

    /**
     * @covers CreateUsers::testGenerateClientSIPAccount
     * @todo   Implement testGenerateClientSIPAccount().
     */
    public function testGenerateClientSIPAccount() {
        // Remove the following lines when you implement this test.
        $this->object->setHas_external_dial('false');
        $this->object->setNazwa_klienta('ProxyAd');
        $this->object->setNr_SIP_c2c('90000');
        $this->object->setNr_SIP_klienta('10000');
        $this->object->setNr_klienta('10000');
        $this->object->setNumer_prezentowany('222468000');
        $this->object->setUser_email('user@mail.com');
        $this->object->setUser_password('user_pass');
        $this->object->setVM_password('voicemail_pass');
        $this->object->set_CreateC2cUser(true);
        $this->object->GenerateClientSIPAccount();
    }

}
